In [6]:
# Import Statemets
import pandas as pd

In [7]:
# Reading the colors dataset
colors = pd.read_csv('/content/colors.csv')
# Looking at the first 5 rows to get a sense of the data
colors.head()

   id            name     rgb is_trans
0  -1         Unknown  0033B2        f
1   0           Black  05131D        f
2   1            Blue  0055BF        f
3   2           Green  237841        f
4   3  Dark Turquoise  008F9B        f

In [8]:
# Let's find out how many different colour LEGO bricks are actually in production
colors['name'].nunique()

135

In [9]:
# figure out how many of the LEGO colours are transparent compared to how many colours are opaque.
# We could also have done colors.is_trans.value_counts()
colors['is_trans'].groupby(colors['is_trans']).count()

is_trans
f    107
t     28
Name: is_trans, dtype: int64

## Playing with markdown in collab

### Understanding Lego Theme vs Lego Sets

Walk into a lego store and you will see their products organized by theme. Their theme include Star wars, Batman, and many more

<img src="https://i.imgur.com/aKcwkSx.png">

A lego **set** is a particular box of Lego product. Therefore a single theme typically has many different sets

In [10]:
# Reading the sets dataset
sets = pd.read_csv('/content/sets.csv')
# Looking at the first 5 rows to get a sense of the data
sets.head()

  set_num                        name  year  theme_id  num_parts
0   001-1                       Gears  1965         1         43
1  0011-2           Town Mini-Figures  1978        84         12
2  0011-3  Castle 2 for 1 Bonus Offer  1987       199          0
3  0012-1          Space Mini-Figures  1979       143         12
4  0013-1          Space Mini-Figures  1979       143         12

 Answering some questions from the sets data

In [20]:
# In which year were the first LEGO sets released and what were these sets called?
first_year_set_index = sets['year'].idxmin()
sets.iloc[first_year_set_index][['year', 'name']]

year                          1949
name    Extra-Large Gift Set (ABB)
Name: 9521, dtype: object

In [23]:
# How many different products did the LEGO company sell in their first year of operation?
sets[sets['year'] == 1949]

      set_num                               name  year  theme_id  num_parts
9521  700.1-1         Extra-Large Gift Set (ABB)  1949       365        142
9534  700.2-1               Large Gift Set (ABB)  1949       365        178
9539  700.3-1              Medium Gift Set (ABB)  1949       365        142
9544  700.A-1              Small Brick Set (ABB)  1949       371         24
9545  700.B-1  Small Doors and Windows Set (ABB)  1949       371         12

In [24]:
# What are the top 5 LEGO sets with the most number of parts? 
sets.sort_values('num_parts', ascending=False).head()

        set_num                           name  year  theme_id  num_parts
15004  BIGBOX-1  The Ultimate Battle for Chima  2015       571       9987
11183   75192-1          UCS Millennium Falcon  2017       171       7541
10551   71043-1                Hogwarts Castle  2018       246       6020
295     10256-1                      Taj Mahal  2017       673       5923
221     10189-1                      Taj Mahal  2008       673       5922

In [28]:
# Now let's take a look at how many sets the LEGO company has published year-on-year. 
sets.groupby('year').count()['set_num']

year
1949      5
1950      6
1953      4
1954     14
1955     28
       ...
2017    786
2018    816
2019    840
2020    674
2021      3
Name: set_num, Length: 71, dtype: int64