In [ ]:
# Read the csv file with pandas, column should be 'DATE', 'TAG', 'POSTS'
# Setting the header row to 0 allows us to skip the first row, which was the old column names
import pandas as pd
df = pd.read_csv('/content/QueryResults.csv', names=['DATE', 'TAG', 'POSTS'], header=0)

## Data Exploration

In [10]:
# Show the first 5 rows
df.head()

                  DATE         TAG  POSTS
0  2008-07-01 00:00:00          c#      3
1  2008-08-01 00:00:00    assembly      8
2  2008-08-01 00:00:00  javascript    162
3  2008-08-01 00:00:00           c     85
4  2008-08-01 00:00:00      python    124

In [11]:
# show the last 5 rows
df.tail()

                     DATE    TAG  POSTS
1986  2020-07-01 00:00:00      r   5694
1987  2020-07-01 00:00:00     go    743
1988  2020-07-01 00:00:00   ruby    775
1989  2020-07-01 00:00:00   perl    182
1990  2020-07-01 00:00:00  swift   3607

In [12]:
# How many rows and columns?
df.shape

(1991, 3)

In [14]:
# Let's see which Tags have the most posts
df[['TAG', 'POSTS']].groupby('TAG').sum().sort_values('POSTS', ascending=False).head()

              POSTS
TAG
javascript  2056510
java        1696403
python      1496210
c#          1423530
php         1361988